# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suspect2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(280, 0, 411, 41))
        self.label1.setObjectName("label1")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(300, 50, 330, 439))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.photo_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_8.setText("")
        self.photo_8.setObjectName("photo_8")
        self.gridLayout_4.addWidget(self.photo_8, 4, 1, 1, 1)
        self.photo_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_2.setText("")
        self.photo_2.setObjectName("photo_2")
        self.gridLayout_4.addWidget(self.photo_2, 0, 1, 1, 1)
        self.suspect5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect5.setObjectName("suspect5")
        self.gridLayout_4.addWidget(self.suspect5, 3, 1, 1, 1)
        self.suspect6 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect6.setObjectName("suspect6")
        self.gridLayout_4.addWidget(self.suspect6, 3, 2, 1, 1)
        self.photo_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_3.setText("")
        self.photo_3.setObjectName("photo_3")
        self.gridLayout_4.addWidget(self.photo_3, 0, 2, 1, 1)
        self.photo_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_4.setText("")
        self.photo_4.setObjectName("photo_4")
        self.gridLayout_4.addWidget(self.photo_4, 2, 0, 1, 1)
        self.suspect2_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect2_2.setObjectName("suspect2_2")
        self.gridLayout_4.addWidget(self.suspect2_2, 1, 1, 1, 1)
        self.suspect3_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect3_2.setObjectName("suspect3_2")
        self.gridLayout_4.addWidget(self.suspect3_2, 1, 2, 1, 1)
        self.photo_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_6.setText("")
        self.photo_6.setObjectName("photo_6")
        self.gridLayout_4.addWidget(self.photo_6, 2, 2, 1, 1)
        self.photo_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_5.setText("")
        self.photo_5.setObjectName("photo_5")
        self.gridLayout_4.addWidget(self.photo_5, 2, 1, 1, 1)
        self.suspect4_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect4_2.setObjectName("suspect4_2")
        self.gridLayout_4.addWidget(self.suspect4_2, 3, 0, 1, 1)
        self.photo_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_9.setText("")
        self.photo_9.setObjectName("photo_9")
        self.gridLayout_4.addWidget(self.photo_9, 4, 2, 1, 1)
        self.photo_1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_1.setText("")
        self.photo_1.setObjectName("photo_1")
        self.gridLayout_4.addWidget(self.photo_1, 0, 0, 1, 1)
        self.photo_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.photo_7.setText("")
        self.photo_7.setObjectName("photo_7")
        self.gridLayout_4.addWidget(self.photo_7, 4, 0, 1, 1)
        self.suspect1_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect1_2.setObjectName("suspect1_2")
        self.gridLayout_4.addWidget(self.suspect1_2, 1, 0, 1, 1)
        self.suspect7 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect7.setObjectName("suspect7")
        self.gridLayout_4.addWidget(self.suspect7, 5, 0, 1, 1)
        self.suspect8 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect8.setObjectName("suspect8")
        self.gridLayout_4.addWidget(self.suspect8, 5, 1, 1, 1)
        self.suspect9 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.suspect9.setObjectName("suspect9")
        self.gridLayout_4.addWidget(self.suspect9, 5, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 218, 293))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.suspect3_f = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.suspect3_f.setObjectName("suspect3_f")
        self.gridLayout_2.addWidget(self.suspect3_f, 5, 0, 1, 1)
        self.suspect1_f = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.suspect1_f.setObjectName("suspect1_f")
        self.gridLayout_2.addWidget(self.suspect1_f, 3, 0, 1, 1)
        self.suspect4_f = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.suspect4_f.setObjectName("suspect4_f")
        self.gridLayout_2.addWidget(self.suspect4_f, 5, 1, 1, 1)
        self.photo_f3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.photo_f3.setText("")
        self.photo_f3.setObjectName("photo_f3")
        self.gridLayout_2.addWidget(self.photo_f3, 4, 0, 1, 1)
        self.photo_f1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.photo_f1.setText("")
        self.photo_f1.setObjectName("photo_f1")
        self.gridLayout_2.addWidget(self.photo_f1, 2, 0, 1, 1)
        self.photo_f4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.photo_f4.setText("")
        self.photo_f4.setObjectName("photo_f4")
        self.gridLayout_2.addWidget(self.photo_f4, 4, 1, 1, 1)
        self.suspect2_f = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.suspect2_f.setObjectName("suspect2_f")
        self.gridLayout_2.addWidget(self.suspect2_f, 3, 1, 1, 1)
        self.photo_f2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.photo_f2.setText("")
        self.photo_f2.setObjectName("photo_f2")
        self.gridLayout_2.addWidget(self.photo_f2, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, -10, 48, 16))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 490, 331, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.next = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 330, 191, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.photo_c2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.photo_c2.setText("")
        self.photo_c2.setObjectName("photo_c2")
        self.gridLayout_3.addWidget(self.photo_c2, 2, 1, 1, 1)
        self.photo_c3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.photo_c3.setText("")
        self.photo_c3.setObjectName("photo_c3")
        self.gridLayout_3.addWidget(self.photo_c3, 3, 0, 1, 1)
        self.photo_c1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.photo_c1.setText("")
        self.photo_c1.setObjectName("photo_c1")
        self.gridLayout_3.addWidget(self.photo_c1, 2, 0, 1, 1)
        self.photo_c4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.photo_c4.setText("")
        self.photo_c4.setObjectName("photo_c4")
        self.gridLayout_3.addWidget(self.photo_c4, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 300, 91, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.photo_1.setPixmap(QtGui.QPixmap("show/1.png"))
        self.photo_2.setPixmap(QtGui.QPixmap("show/2.png"))
        self.photo_3.setPixmap(QtGui.QPixmap("show/3.png"))
        self.photo_4.setPixmap(QtGui.QPixmap("show/4.png"))
        self.photo_5.setPixmap(QtGui.QPixmap("show/5.png"))
        self.photo_6.setPixmap(QtGui.QPixmap("show/6.png"))
        self.photo_7.setPixmap(QtGui.QPixmap("show/7.png"))
        self.photo_8.setPixmap(QtGui.QPixmap("show/8.png"))
        self.photo_9.setPixmap(QtGui.QPixmap("show/9.png"))
        files = os.listdir("choice/")  # 读入文件夹
        names = []
        for i in files:
            names.append("choice/"+i)
        print(names)
        self.suspect1_2.clicked.connect(self.saveChoice)
        self.suspect2_2.clicked.connect(self.saveChoice)
        self.suspect3_2.clicked.connect(self.saveChoice)
        self.suspect4_2.clicked.connect(self.saveChoice)
        self.suspect5.clicked.connect(self.saveChoice)
        self.suspect6.clicked.connect(self.saveChoice)
        self.suspect7.clicked.connect(self.saveChoice)
        self.suspect8.clicked.connect(self.saveChoice)
        self.suspect9.clicked.connect(self.saveChoice)
        self.suspect1_f.clicked.connect(self.saveChoice)
        self.suspect2_f.clicked.connect(self.saveChoice)
        self.suspect3_f.clicked.connect(self.saveChoice)
        self.suspect4_f.clicked.connect(self.saveChoice)
        self.stop.clicked.connect(self.saveChoice)




        self.photo_f1.setPixmap(QtGui.QPixmap(names[0]))
        self.photo_f2.setPixmap(QtGui.QPixmap(names[1]))
        self.photo_f3.setPixmap(QtGui.QPixmap(names[2]))
        self.photo_f4.setPixmap(QtGui.QPixmap(names[3]))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "chose four image that look like the suspect, untill you found suspect"))
        self.suspect5.setText(_translate("MainWindow", "suspect5"))
        self.suspect6.setText(_translate("MainWindow", "suspect6"))
        self.suspect2_2.setText(_translate("MainWindow", "suspect2"))
        self.suspect3_2.setText(_translate("MainWindow", "suspect3"))
        self.suspect4_2.setText(_translate("MainWindow", "suspect4"))
        self.suspect1_2.setText(_translate("MainWindow", "suspect1"))
        self.suspect7.setText(_translate("MainWindow", "suspect7"))
        self.suspect8.setText(_translate("MainWindow", "suspect8"))
        self.suspect9.setText(_translate("MainWindow", "suspect9"))
        self.suspect3_f.setText(_translate("MainWindow", "suspect3_f"))
        self.suspect1_f.setText(_translate("MainWindow", "suspect1_f"))
        self.suspect4_f.setText(_translate("MainWindow", "suspect4_f"))
        self.suspect2_f.setText(_translate("MainWindow", "suspect2_f"))
        self.label.setText(_translate("MainWindow", "last one"))
        self.stop.setText(_translate("MainWindow", "i found suspect"))
        self.next.setText(_translate("MainWindow", "next"))
        self.label_3.setText(_translate("MainWindow", "your choice"))
    def saveChoice(self):
        button_name = QtWidgets.QWidget().sender().objectName()
        source = "show/" + button_name[-1] + ".png"
        destination = "choice/" + button_name[-1] + ".png"
        copyfile(source, destination)
        files = os.listdir("choice/")  # 读入文件夹
        num_png = len(files)  # 统计文件夹中的文件个数
        num_p =[]
        for i in files:
            num_p.append(i[7]-1)
        # # Suppression images dans répertoires pictures_showed
        # py_files = glob.glob("show/img*.png")
        # for py_file in py_files:
        #     os.remove(py_file)
        #
        # # Choix de l'utilisateur :
        # files = os.listdir("choice/")  # 读入文件夹
        # num_png = len(files)  # 统计文件夹中的文件个数
        # num_p =[]
        # for i in files:
        #     num_p.append(i[7]-1)
        #
        # # new_index=random.sample(index, n)
        # # encoded_choix=[None]*n
        # for i in range(n):
        #     encoded_choix[i]=encoded_imgs[num_p[i]]
        #
        # # Algo genetique1 : crossover
        # print(type(encoded_choix))
        # print(type(encoded_choix[0]))
        # #np.save('encoded_choix', encoded_choix)
        # encoded_ag = ag.crossover_pixels(encoded_choix, 0.3)
        # decoded_ag = decoder_.predict(encoded_ag)
        # nn.save_reconstruction(12, decoded_ag)
        #
        # # Choix de l'utilisateur2 : PUJIAN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        # mylist = list(range(0,12,1))
        # index = random.sample(mylist, 4)
        # new_index=random.sample(index, 4)
        # encoded_choix=[None]*4
        # for i in range(4):
        #     encoded_choix[i]=np.array(encoded_ag[new_index[i]])
        #
        # # Algo genetique2 : crossover
        # print(type(encoded_choix))
        # print(type(encoded_choix[0]))
        # encoded_ag = ag.crossover_pixels(encoded_choix, 0.3)
        # print(type(encoded_ag[0]))
        # decoded_ag = decoder_.predict(encoded_ag)
        # #nn.save_reconstruction(12, decoded_ag)
        #
        #
        # # Choix de l'utilisateur2 : PUJIAN!!!!!!!!!!!!!!!!
        # mylist = list(range(0,12,1))
        # index = random.sample(mylist, 4)
        # new_index=random.sample(index, 4)
        # encoded_choix=[None]*4
        # for i in range(4):
        #     encoded_choix[i]=np.array(encoded_ag[new_index[i]])

        app = QtWidgets.QApplication(sys.argv)
        #MainWindow = QMainWindow()
        main=QtWidgets.QWidget()
        latout = QtWidgets.QHBoxLayout()
        main.setLayout(latout)


        if num_png ==1:
            QtWidgets.QApplication.processEvents()
            self.photo_c1.setPixmap(QtGui.QPixmap(destination))
        elif num_png ==2:
            QtWidgets.QApplication.processEvents()
            self.photo_c2.setPixmap(QtGui.QPixmap(destination))
        elif num_png == 3:
            QtWidgets.QApplication.processEvents()
            self.photo_c3.setPixmap(QtGui.QPixmap(destination))
        elif num_png == 4:
            QtWidgets.QApplication.processEvents()
            self.photo_c4.setPixmap(QtGui.QPixmap(destination))
        elif num_png >= 5:
            QtWidgets.QApplication.processEvents()
            rmtree('choice/')
            os.mkdir('choice/')
            self.photo_c2.setPixmap(QtGui.QPixmap())
            self.photo_c3.setPixmap(QtGui.QPixmap())
            self.photo_c4.setPixmap(QtGui.QPixmap())
            self.photo_c1.setPixmap(QtGui.QPixmap(destination))
